### ISSUE TITLE
Can't launch at all

### ISSUE THREAD

**Issue by zeglin** [JijaProGamer/playwright-anti-fingerprinter#5]
node profile01.mjs 

file:///bots/node_modules/playwright-anti-fingerprinter/index.js:110
        throw new Error(`browser type "${browserType}" is not supported. Please use ${supportedDrivers.join(" or ")}.`)
              ^

Error: browser type "[object Object]" is not supported. Please use firefox.
    at GenerateFingerprint (file:///bots/node_modules/playwright-anti-fingerprinter/index.js:110:15)
    at file:///bots/profile01.mjs:20:25
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

Node.js v18.1.0

**Comment by JijaProGamer** [comment]
You aren't using the module currently, you are passing a object (maybe the browser) to browser type, which is supposed to be a string "chrome", "firefox", etc
